### ISSUE TITLE
Blender 2.79 addon not showing

### ISSUE THREAD

**Issue by Abukaff** [feliwir/W3D-Tools#6]
Hello, 
On blender 2.79 i installed the addon through the user pref, however it is not showing.

I used the release 1.0 "import_w3d.py"

**Comment by feliwir** [comment]
Hello, you must install the .zip archive, not a single python file

**Comment by Abukaff** [comment]
Thanks for your fast reply ! it worked ! however i dont know if this is of your concern, but extracted a W3D from cnc generals, when importing im getting the following error

Cannot load image ABPATRIOT
Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\w3dtools\__init__.py", line 68, in execute
    import_w3d.MainImport(self.filepath, context, self)
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\w3dtools\import_w3d.py", line 1383, in MainImport
    mesh_ob.parent = bpy.data.objects[amtName]
KeyError: 'bpy_prop_collection[key]: key "" not found'

location: <unknown location>:-1

**Comment by Tarcontar** [comment]
The texture files of the model should be in the same folder als the w3d file. Otherwise they are not found.
Tarcontar

**Comment by Abukaff** [comment]
i've never tried to comment on any Github project before, and when i did for the first time i was amazed.
You guys are awesome thank you !
