### ISSUE TITLE
Unknown chunktype in file errors when importing a w3d model from a game

### ISSUE THREAD

**Issue by 8bit-coder** [feliwir/W3D-Tools#7]
I've been trying to open some w3d files I found inside of a game(A crappy flash hotwheels game that came in a cereal box) and I confirmed the add-on was working, by importing the sample bone model. Except when I try to import the game's files, it won't work. Here is a zip containing the w3d files that failed importing:

[Game_W3d_Files.zip](https://github.com/sage-team/W3D-Tools/files/1933269/Game_W3d_Files.zip)

**Comment by feliwir** [comment]
I am guessing that's a different .w3d format you've encountered. This decoder is only meant for .w3d files that are part of EA sage games.

**Comment by 8bit-coder** [comment]
Oh, alright then.
